services:
  - type: worker
    name: musenzy-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: OWNER_ID
        sync: false
      - key: MAX_QUEUE_SIZE
        value: "20"
      - key: DEFAULT_VOLUME
        value: "100"
      - key: DOWNLOAD_DIR
        value: "/tmp/musenzy"
    disk:
      name: musenzy-data
      mountPath: /app/data
      sizeGB: 1
